### ISSUE TITLE
Getting Errors on the Elastic Container

### ISSUE THREAD

**Issue by kennyparsons** [AnalogJ/lodestone#63]
After only modifying the compose file to use my own reverse proxy, I'm getting the following error on the Elastic container:

The compose file is run by root, the directory is owned by root:
```
drwxr-xr-x 4 root root 4096 Feb  7 13:59 data
```

Log:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.,
{"type": "server", "timestamp": "2020-02-07T19:59:23,457+0000", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "elasticsearch",  "message": "uncaught exception in thread [main]" , ,
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",,
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",,
"at org.elasticsearch.node.Node.<init>(Node.java:580) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"... 6 more",,
"Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",,
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",,
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",,
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",,
"at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",,
"at java.nio.file.Files.createDirectory(Files.java:692) ~[?:?]",,
"at java.nio.file.Files.createAndCheckIsDirectory(Files.java:799) ~[?:?]",,
"at java.nio.file.Files.createDirectories(Files.java:785) ~[?:?]",,
"at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:271) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:208) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:268) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.node.Node.<init>(Node.java:271) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.2.1.jar:7.2.1]",,
"... 6 more"] },
```

**Comment by AnalogJ** [comment]
Looks like this issue may be related to permissions issue. https://github.com/elastic/helm-charts/issues/258

Inside the elasticsearch container, we're running as:

```
uid=0(root) gid=0(root) groups=0(root)
```
Can you confirm thats the same on your host: `$ id root`?

**Comment by kennyparsons** [comment]
```
/elasticsearch# id root
uid=0(root) gid=0(root) groups=0(root)
```

```
elasticsearch# ls -alt
total 8
drwxr-xr-x 4 root root 4096 Feb  7 13:59 ..
drwxr-xr-x 2 root root 4096 Feb  7 13:59 .
```

**Comment by AnalogJ** [comment]
Do you have time to jump on gitter with me? I want to figure out whats going on here

https://gitter.im/lodestone-chat/community

**Comment by kennyparsons** [comment]
I can latter. Thanks.

**Comment by AnalogJ** [comment]
So the current workaround for this issue is to create the `./data/elasticseach` directory and then `chown -R 1000:root ./data/elasticseach`

I'm working on implementing a fix to the elasticsearch container itself so this is unnecessary.

**Comment by AnalogJ** [comment]
This issue has now been fixed via https://github.com/AnalogJ/lodestone/commit/d3d88289503d3fd14220300b9168b25eec88301f
